# Use the official Metabase image as the base image
FROM metabase/metabase:latest

# Optional: You can add custom configurations or modifications here
# For example, if you want to set environment variables or add files:
# ENV MB_DB_TYPE=mysql
# COPY my_custom_file /path/to/file

# Expose the port that Metabase listens on
EXPOSE 3000
